version: '3'

services:

  nginx:
    image: nginx
    ports: 
      - 80:80
    restart: unless-stopped
    volumes:
    - back_static:/home/app/back/static
    - back_media:/home/app/back/media  
    - ./nginx.conf:/etc/nginx/conf.d/default.conf

    networks:
      - app-network

volumes:
  back_static:
  back_media:
  back_db_data:



networks:
  app-network:
    driver: bridge
